### ISSUE TITLE
リナックスのコマンドを勉強している人です

### ISSUE THREAD

**Issue by hongsh0918** [DokBak/DokBak_Shell_CMD#1]
ShellScriptCommand.shファイルの共有ありがとうございます！
凄い参考になります！
ShellScriptCommand.shを実行してリナックスコマンドリストでコマンドの番号を入力する時に、番号に0を付けて検索すると番号とコマンドの説明がずれてるところがありました。

ex) 
番号#コマンド
023 # find 
検索コマンド -> 23入力時、findコマンドの説明が表示される。
検索コマンド -> 023入力時、exitコマンドの説明が表示される。

一応共有しておきます！
また勉強しながら気になることとかあったら質問したいと思いますので宜しくお願い致します！！

**Comment by DokBak** [comment]
ご指摘ありがとうございます。
指摘したバグについて修正しました。
